### ISSUE TITLE
Add to OpenUPM

### ISSUE THREAD

**Issue by EarMaster** [JohnBaracuda/com.baracuda.runtime-monitoring#2]
Add this to OpenUPM for easy installation via the Package Manager (and no clutter in the Assets directory):
https://openupm.com/docs/adding-upm-package.html#upm-package-criteria

**Comment by JohnBaracuda** [comment]
I will definitely do that once the project has reached a certain level of compatibility and enough testing has been done.

**Comment by JohnBaracuda** [comment]
Version 3.0.1 (and later) are now available at OpenUPM  https://openupm.com/packages/com.baracuda.runtime-monitoring/
